name: panda-env
channels:
  - defaults
dependencies:
  - ca-certificates=2020.6.24
  - certifi=2020.6.20
  - libcxx=10.0.0
  - libedit=3.1.20191231
  - libffi=3.3
  - ncurses=6.2
  - openssl=1.1.1g
  - pip=20.1.1
  - python=3.7.7
  - readline=8.0
  - setuptools=47.3.1
  - sqlite=3.32.3
  - tk=8.6.10
  - wheel=0.34.2
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - numpy==1.19.0
    - pybullet==2.8.3

